# sign in at https://travis-ci.org/#
#
# http://docs.travis-ci.com/user/languages/objective-c/
language: objective-c
xcode_sdk:
  - iphonesimulator7.1
  - iphonesimulator7.0
  - iphonesimulator6.1
xcode_project: MROGeometry.xcodeproj
xcode_scheme: MROGeometry
